services:
  - type: web
    name: haunted-mansion-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 8000
